[package]
name = "immix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
int-enum = "0.5.0"
libc = "0.2"
parking_lot = "0.12.1"
rustc-hash = "1.1.0"
lazy_static = "1.4.0"
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser","memoryapi"] }

[dev-dependencies]
rand = "0.8.5"
criterion = "0.3"

[[bench]]
name = "immix_bench"
harness = false