[package]
name = "immix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
parking_lot = "0.12.1"
rustc-hash = "1.1.0"
